<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="ScreenShot" duration-ms="33899" started-at="2021-04-03T04:57:36Z" finished-at="2021-04-03T04:58:09Z">
    <groups>
    </groups>
    <test name="BankApplication" duration-ms="33899" started-at="2021-04-03T04:57:36Z" finished-at="2021-04-03T04:58:09Z">
      <class name="com.ba.testcase.TestCase001">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.ba.testcase.TestCase001@2eee9593]" name="setup" is-config="true" duration-ms="13906" started-at="2021-04-03T10:27:36Z" finished-at="2021-04-03T10:27:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="tc001()[pri:0, instance:com.ba.testcase.TestCase001@2eee9593]" name="tc001" duration-ms="18325" started-at="2021-04-03T10:27:50Z" finished-at="2021-04-03T10:28:08Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Googel] but found [Google]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Googel] but found [Google]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at com.ba.testcase.TestCase001.tc001(TestCase001.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:663)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:849)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1157)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc001 -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:com.ba.testcase.TestCase001@2eee9593]" name="teardown" is-config="true" duration-ms="1067" started-at="2021-04-03T10:28:08Z" finished-at="2021-04-03T10:28:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.ba.testcase.TestCase001 -->
    </test> <!-- BankApplication -->
  </suite> <!-- ScreenShot -->
</testng-results>
